name: "log_beaver"
version: "1.0.0"
config-version: 2

profile: "log_beaver"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  log_beaver:
    staging:
      +materialized: view
    marts:
      +materialized: table
