log_beaver:
  target: dev
  outputs:
    dev:
      type: clickhouse
      schema: "{{ env_var('CLICKHOUSE_DB', 'log_beaver') }}"
      host: "{{ env_var('CLICKHOUSE_HOST', 'clickhouse') }}"
      port: "{{ env_var('CLICKHOUSE_HTTP_PORT', '8123') | int }}"
      user: "{{ env_var('CLICKHOUSE_USER', 'log_beaver') }}"
      password: "{{ env_var('CLICKHOUSE_PASSWORD', 'log_beaver') }}"
      secure: false
      verify: false
      threads: 4
